### ISSUE TITLE
Single Manager View 

### ISSUE THREAD

**Issue by znivz** [inunes1904/APIcapstone#4]
We need to do the Single Manager View, and solve the manager role to user.

**Comment by inunes1904** [comment]
hmmmmm just like this ?

class ManagersView(generics.ListCreateAPIView):
    throttle_classes = [AnonRateThrottle, UserRateThrottle]
    queryset = User.objects.filter(groups__name='Manager')
    serializer_class = ManagerSerializer
    permission_classes = [IsAuthenticated, IsManager | IsAdminUser]

    def post(self, request, *args, **kwargs):
        # return Response({"message": "ok"})
        username = request.data['username']
        if username:
            user = get_object_or_404(User, username=username)
            managers = Group.objects.get(name='Manager')
            managers.user_set.add(user) #type: ignore
            return Response({'message':'User added to Manager group'}, status.HTTP_201_CREATED)
        return Response({'message': 'error'}, status.HTTP_400_BAD_REQUEST)

**Comment by inunes1904** [comment]
Done! Solved just going to push the code back
